version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: vsml-backend
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/data:/app/data
    restart: unless-stopped
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: vsml-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=/api

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: vsml-nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx:/etc/nginx/conf.d
    restart: unless-stopped